wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1680637751.728296
    t:
      1:
      - 1
      - 11
      - 12
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 12
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 16
      - 19
      - 23
      4: 3.10.9
      5: 0.14.0
      6: 4.27.4
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 10
len_train:
  desc: null
  value: 378
len_val:
  desc: null
  value: 114
lr:
  desc: null
  value: 0.0003
lr_scheduler:
  desc: null
  value: 0.9
